name: 'pysen-test'
description: 'Run pysen test'
inputs:
  path:
    description: 'Path to codebase'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  entrypoint: "bin/bash"
  args:
    - "-c"
    - 'ls -la; tox --parallel'
