name: 'pysen-test'
description: 'Run pysen test'
runs:
  using: 'docker'
  image: 'Dockerfile'
  entrypoint: '/bin/bash'
  args:
    - '-c'
    - 'git status && git diff --abbrev=40 --full-index -M --raw -z --no-color'
