name: 'pysen-test'
description: 'Run pysen test'
runs:
  using: 'docker'
  image: 'Dockerfile'
  entrypoint: '/bin/bash'
  args:
    - '-c'
    - "git config --global --add safe.directory $(pwd) && git status && tox --parallel"
