name: pysen-test
on:
  push:
    branches:
  pull_request: {}
jobs:
  tox:
    name: Run pysen-test
    runs-on: ubuntu-20.04
    timeout-minutes: 15
    container:
      image: quay.io/pysen/pysen-test@sha256:a37dbee9ecc51ee5240deb275001a459ec177eb4e7b3666ae00088db102c6b9d
    steps:
    - uses: actions/checkout@v2
      with:
        lfs: false
        path: ${{ env.CHECKOUT_PATH }}
    - name: Run tox
      run: |
        tox --parallel
